name: 'action test'
description: 'Grabbing environment and secrets for a custom action script'
author: 'ohookins'

inputs:
  type-of-animal:
    required: true

outputs:
  greeting:
    value: ${{ steps.script1.outputs.test_output_1 }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - id: get_last_commit_hash
      shell: bash
      run: |
        echo "LAST_COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> ${GITHUB_ENV}
    - id: script1
      run: $GITHUB_ACTION_PATH/action1.sh
      shell: bash
    - shell: bash
      run: |
        echo "${{ inputs.type-of-animal }}"
    - id: script2
      if: ${{ inputs.type-of-animal != '' }}
      run: $GITHUB_ACTION_PATH/action2.sh
      env:
        test-output-1: ${{ steps.script1.outputs.test_output_1 }}
        type-of-animal: ${{ inputs.type-of-animal }}
        animal: ${{ inputs.animal }}
      shell: bash
