name: 'action test'
description: 'Grabbing environment and secrets for a custom action script'
author: 'ohookins'

outputs:
  greeting:
    value: ${{ steps.script1.outputs.test_output_1 }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - id: get_last_commit_hash
      shell: bash
      run: |
        echo "LAST_COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> ${GITHUB_ENV}
    - id: script1
      run: $GITHUB_ACTION_PATH/action1.sh
      shell: bash
    - id: script2
      run: $GITHUB_ACTION_PATH/action2.sh
      shell: bash
